Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -43,17 +43,25 @@ jobs:
           npx playwright test --reporter=line,allure-playwright
         continue-on-error: true  # Allow tests to fail without stopping the workflow
 
+      - name: Merge Playwright Reports
+        run: npx playwright merge-reports --output allure-results
+        if: always()
+      
       - name: Generate Allure Report
         run: |
-          allure generate allure-results --clean -o allure-report
-        if: always()  # Ensure this step runs even if the previous step fails
+          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
+            allure generate allure-results --clean -o allure-report
+          else
+            echo "No Allure results found. Skipping report generation."
+          fi
+        if: always()
 
       - name: Upload Allure Report
+        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: allure-report
           path: allure-report
-        if: always()  # Ensure this step runs even if the previous step fails
 
   publish-allure-report:
     needs: test  # Runs after the test job
@@ -70,13 +78,23 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: allure-report
+      
+      - name: Verify Allure Report Before Deploying
+        run: |
+          if [ -d "allure-report" ] && [ "$(ls -A allure-report)" ]; then
+              echo "Allure Report found. Proceeding with deployment."
+          else
+              echo "No Allure report found. Failing the job."
+              exit 1
+          fi
 
-      - name: Deploy Allure Report to Report branch # git hub pages have permission issues i think
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_branch: report-branch
-          publish_dir: allure-report
+          - name: Deploy Allure Report to Report branch
+          uses: peaceiris/actions-gh-pages@v3
+          with:
+            personal_token: ${{ secrets.GH_PAGES_TOKEN }}
+            publish_branch: report-branch
+            publish_dir: allure-report
+  
 
   notify:
     needs: test  # Runs after the test job
